name: Pull Request Checks

on:
  pull_request:
    branches: [main, develop]

jobs:
  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test -- --run

      - name: Build project
        run: npm run build

      - name: Comment PR with build size
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            function getFolderSize(folderPath) {
              let totalSize = 0;
              const files = fs.readdirSync(folderPath);
              
              files.forEach(file => {
                const filePath = path.join(folderPath, file);
                const stats = fs.statSync(filePath);
                
                if (stats.isDirectory()) {
                  totalSize += getFolderSize(filePath);
                } else {
                  totalSize += stats.size;
                }
              });
              
              return totalSize;
            }
            
            function formatBytes(bytes) {
              if (bytes === 0) return '0 Bytes';
              const k = 1024;
              const sizes = ['Bytes', 'KB', 'MB', 'GB'];
              const i = Math.floor(Math.log(bytes) / Math.log(k));
              return Math.round((bytes / Math.pow(k, i)) * 100) / 100 + ' ' + sizes[i];
            }
            
            try {
              const distSize = getFolderSize('./dist');
              const sizeFormatted = formatBytes(distSize);
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `### 📦 Build Size Report\n\n**Total build size:** ${sizeFormatted}\n\n✅ All checks passed!`
              });
            } catch (error) {
              console.error('Error creating PR comment:', error);
            }

